'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ItemCheck

    '''<summary>
    '''Grid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grid As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''ContentControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentControl1 As Global.DevExpress.Web.ContentControl

    '''<summary>
    '''ASPxLabel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel1 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''editItemCheckCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents editItemCheckCode As Global.DevExpress.Web.ASPxGridViewTemplateReplacement

    '''<summary>
    '''editItemCheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents editItemCheck As Global.DevExpress.Web.ASPxGridViewTemplateReplacement

    '''<summary>
    '''editUnitMeasurement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents editUnitMeasurement As Global.DevExpress.Web.ASPxGridViewTemplateReplacement

    '''<summary>
    '''editDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents editDescription As Global.DevExpress.Web.ASPxGridViewTemplateReplacement

    '''<summary>
    '''editActiveStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents editActiveStatus As Global.DevExpress.Web.ASPxGridViewTemplateReplacement

    '''<summary>
    '''UpdateButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateButton As Global.DevExpress.Web.ASPxGridViewTemplateReplacement

    '''<summary>
    '''CancelButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelButton As Global.DevExpress.Web.ASPxGridViewTemplateReplacement

    '''<summary>
    '''HF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HF As Global.DevExpress.Web.ASPxHiddenField

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As PECGI_SPC.Site
        Get
            Return CType(MyBase.Master, PECGI_SPC.Site)
        End Get
    End Property
End Class
