Public Class clsProdSampleVerification
    Public Property FactoryCode As String
    Public Property FactoryName As String
    Public Property LineCode As String
    Public Property LineName As String
    Public Property ItemCheck_Code As String
    Public Property ItemCheck_Name As String
    Public Property ItemType_Code As String
    Public Property ItemType_Name As String
    Public Property Period As String
    Public Property ProdDate As String
    Public Property ShiftCode As String
    Public Property ShiftName As String
    Public Property SeqCode As String
    Public Property SeqName As String
    Public Property User As String
    Public Property CODE As String
    Public Property CODENAME As String
    Public Property ProdDate_Grid As String
    Public Property Shiftcode_Grid As String
    Public Property SPCResultID As String
    Public Property ActivityID As String
    Public Property Action As String
    Public Property Result As String
    Public Property Remark As String
    Public Property PIC As String
    Public Property Seq As String
    Public Property Time As String
End Class
