Public Class ClsTCCSResultApproval
    Public Property TCCSResultID As String
    Public Property MachineNo As String
    Public Property PartID As String
    Public Property RevNo As Integer
    Public Property RevDate As Date
    Public Property RevHistory As String
    Public Property PreparedBy As String
    Public Property ApprovalStatus1 As String
    Public Property ApprovalDate1 As Date
    Public Property ApprovalPIC1 As String
    Public Property ApprovalJudgement1 As String
    Public Property ApprovalStatus2 As String
    Public Property ApprovalDate2 As Date
    Public Property ApprovalPIC2 As String
    Public Property ApprovalJudgement2 As String
    Public Property ApprovalStatus3 As String
    Public Property ApprovalDate3 As Date
    Public Property ApprovalPIC3 As String
    Public Property ApprovalJudgement3 As String
    Public Property ApprovalStatus4 As String
    Public Property ApprovalDate4 As Date
    Public Property ApprovalPIC4 As String
    Public Property ApprovalJudgement4 As String
    Public Property ActiveStatus As String
    Public Property CreateDate As Date
    Public Property CreateUser As String
    Public Property UpdateDate As Date
    Public Property UpdateUser As String
End Class
